import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

test('server hard-codes the permanent 50-location contract',async()=>{const source=await readFile(new URL('../server.js',import.meta.url),'utf8');assert.match(source,/MAX_SORTING_LOCATIONS=50/);assert.match(source,/NO AVAILABLE SORTING LOCATION/);assert.match(source,/process\.env\.DATABASE_URL/);assert.match(source,/process\.env\.PORT/)});
test('server uses one DST-aware America/Chicago instant for rollover and scans',async()=>{const source=await readFile(new URL('../server.js',import.meta.url),'utf8');assert.match(source,/WAREHOUSE_TIME_ZONE='America\/Chicago'/);assert.doesNotMatch(source,/process\.env\.WAREHOUSE_TIME_ZONE/);assert.match(source,/formatToParts/);assert.match(source,/const scannedAt=new Date\(\)/);assert.match(source,/warehouseDateAt\(scannedAt\)/);assert.match(source,/scanned_at\) VALUES/);assert.match(source,/dockflow:assignments/);});
test('schema contains daily cycles, assignments, and all persistent scan fields',async()=>{const schema=await readFile(new URL('../db/schema.sql',import.meta.url),'utf8');for(const table of ['products','sorting_locations','daily_cycles','daily_assignments','boxes','scan_events','exceptions'])assert.match(schema,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));for(const field of ['warehouse_date','location_number','cycle_id','user_id','device_id','scanned_at'])assert.match(schema,new RegExp(field));assert.match(schema,/generate_series\(1,50\)/)});
test('archive API supports grouped dates, filters, and CSV export',async()=>{const source=await readFile(new URL('../server.js',import.meta.url),'utf8');for(const route of ['/api/archive','/api/archive/export'])assert.match(source,new RegExp(route.replaceAll('/','\\/')));for(const filter of ['sku','boxId','inbound','client','location'])assert.match(source,new RegExp(filter));assert.match(source,/content-type.*text\/csv/);assert.match(source,/warehouse_date BETWEEN/);assert.match(source,/scan_events_archive_date_idx/)});
test('frontend uses same-origin APIs and exposes daily numbered assignments',async()=>{const source=await readFile(new URL('../app.jsx',import.meta.url),'utf8');assert.match(source,/fetch\(path,opts\)/);assert.match(source,/\/api\/scans/);assert.match(source,/Today’s assignments/);assert.match(source,/Start New Day \/ Reset/);assert.match(source,/MOVE BOX TO/);assert.doesNotMatch(source,/Import locations/)});
test('frontend confirms admin day reset and shows rollover provenance',async()=>{const source=await readFile(new URL('../app.jsx',import.meta.url),'utf8');assert.match(source,/Start a new operating day/);assert.match(source,/Confirm as admin/);assert.doesNotMatch(source,/role:'supervisor'/);assert.match(source,/Started automatically/);assert.match(source,/Started manually/);});
test('frontend exposes expandable archive records and CSV filters',async()=>{const source=await readFile(new URL('../app.jsx',import.meta.url),'utf8');for(const text of ['History / Archive','Export CSV','archive-folder','inbound','client','location'])assert.match(source,new RegExp(text.replace(/[ /]/g,'[ /]')));assert.match(source,/\/api\/archive\/\$\{date\}/)});
test('PWA shell is installable, caches CDN dependencies, and never caches mutable API data',async()=>{const manifest=await readFile(new URL('../manifest.webmanifest',import.meta.url),'utf8');const worker=await readFile(new URL('../sw.js',import.meta.url),'utf8');const html=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.match(manifest,/"display":\s*"standalone"/);assert.match(manifest,/icon-192\.png/);assert.match(manifest,/icon-512\.png/);assert.match(worker,/unpkg\.com\/react@18/);assert.match(worker,/unpkg\.com\/react-dom@18/);assert.match(worker,/unpkg\.com\/@babel\/standalone/);assert.match(worker,/Promise\.allSettled/);assert.match(worker,/url\.pathname\.startsWith\('\\/api\\/'\)/);assert.match(worker,/CDN_ORIGINS\.has\(url\.origin\)/);assert.match(worker,/cache\.addAll\(SHELL\)/);assert.match(html,/rel="manifest"/);assert.match(html,/serviceWorker\.register/);});
test('PDA scan mode provides camera fallback and handles detection failures',async()=>{const source=await readFile(new URL('../app.jsx',import.meta.url),'utf8');for(const text of ['PDA Scan','getUserMedia','BarcodeDetector','Manual Box ID or QR payload','LOCATION {destination}','MOVE BOX TO {destination}','detector.detect(video.current)','Camera detection failed','start().catch'])assert.match(source,new RegExp(text.replace(/[{}]/g,'\\$&').replace(/\./g,'\\.')));});
test('README documents the post-merge Neon migration and no manual SQL',async()=>{const readme=await readFile(new URL('../README.md',import.meta.url),'utf8');assert.match(readme,/run the idempotent schema migration once against Neon/);assert.match(readme,/no separate hand-written\/manual SQL requirement/);assert.match(readme,/exactly 50 permanent/)});
test('authentication and RBAC enforce exact roles and protect history from workers',async()=>{const source=await readFile(new URL('../server.js',import.meta.url),'utf8');const schema=await readFile(new URL('../db/schema.sql',import.meta.url),'utf8');for(const text of ['bcrypt','/api/auth/login','/api/auth/logout','HttpOnly','SameSite=Lax','Secure','sessions','roleRank','Insufficient permissions'])assert.match(source,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(source,/path==='\\/api\\/history'/);assert.match(source,/return 'manager'/);assert.match(schema,/role TEXT NOT NULL REFERENCES roles/);});
test('first-admin bootstrap is token-protected, transactional, and one-time',async()=>{const source=await readFile(new URL('../server.js',import.meta.url),'utf8');const schema=await readFile(new URL('../db/schema.sql',import.meta.url),'utf8');for(const text of ['DOCKFLOW_SETUP_TOKEN','x-dockflow-setup-token','timingSafeEqual','requestIsHttps','bootstrapAllowed','dockflow:admin-bootstrap','consumed_at','bcrypt.hash(passcode,12)','INSERT INTO users(email,password_hash,role)','ROLLBACK'])assert.match(source,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(source,/CREATE TABLE IF NOT EXISTS admin_bootstrap/);assert.match(schema,/INSERT INTO admin_bootstrap\(id\)/);});
test('setup UI submits secrets without putting them in the URL',async()=>{const source=await readFile(new URL('../app.jsx',import.meta.url),'utf8');assert.match(source,/location\.pathname==='\/setup'/);assert.match(source,/x-dockflow-setup-token/);assert.match(source,/\/api\/auth\/bootstrap/);assert.doesNotMatch(source,/bootstrap\?token/);});
test('Users page supports role changes and password resets',async()=>{const source=await readFile(new URL('../app.jsx',import.meta.url),'utf8');assert.match(source,/Reset password/);assert.match(source,/update\(u,\{password\}\)/);assert.match(source,/update\(u,\{role:e\.target\.value\}\)/);assert.match(source,/last active admin/);});
test('worker frontend does not request manager-only history',async()=>{const source=await readFile(new URL('../app.jsx',import.meta.url),'utf8');assert.match(source,/user\?\.role==='worker'\?Promise\.resolve\(\[\]\):api\('\\/api\\/history'\)/);assert.match(source,/user\.role==='worker'\?\['PDA Scan','Receiving','Locations','Exceptions'\]/);});
