const {useState,useEffect}=React;
const boxes={'BOX-1042':{boxId:'BOX-1042',sku:'SKU-ALP-01',qty:24,name:'Alpine Trail Bottle'},'BOX-1043':{boxId:'BOX-1043',sku:'SKU-BLU-07',qty:12,name:'Blue Ridge Mug'},'BOX-1044':{boxId:'BOX-1044',sku:'SKU-ALP-01',qty:18,name:'Alpine Trail Bottle'},'BOX-1045':{boxId:'BOX-1045',sku:'SKU-CED-03',qty:8,name:'Cedar Camp Towel'}};
const initial=[{sku:'SKU-ALP-01',name:'Alpine Trail Bottle',done:68,cap:100,loc:'A-01-03'},{sku:'SKU-BLU-07',name:'Blue Ridge Mug',done:44,cap:60,loc:'B-02-01'},{sku:'SKU-CED-03',name:'Cedar Camp Towel',done:31,cap:50,loc:'C-01-02'}];
function App(){const [tab,setTab]=useState('Receiving'),[scan,setScan]=useState(''),[notice,setNotice]=useState(null),[last,setLast]=useState(null),[camera,setCamera]=useState(false),[items,setItems]=useState(initial),[received,setReceived]=useState(147),[exceptions,setExceptions]=useState([{id:1,box:'BOX-1038',reason:'Quantity mismatch · expected 24, found 22',status:'Open'},{id:2,box:'BOX-1029',reason:'Unreadable label',status:'Open'}]);
 useEffect(()=>{if(notice){let t=setTimeout(()=>setNotice(null),3500);return()=>clearTimeout(t)}},[notice]);
 const process=(raw)=>{let key=raw.trim().toUpperCase();let info=boxes[key]||parseQR(key);if(!info){setNotice({red:true,text:'Could not read box. Try BOX-1042 or scan again.'});return}if(last&&last.boxId===info.boxId){setNotice({red:true,text:'Duplicate scan · '+info.boxId+' was already received'});return}let row=items.find(x=>x.sku===info.sku)||items[0];setItems(items.map(x=>x.sku===row.sku?{...x,done:Math.min(x.cap,x.done+info.qty)}:x));setReceived(x=>x+info.qty);setLast(info);setScan('');setNotice({text:`${info.qty} units routed to ${row.loc}`});};
 const parseQR=(s)=>{let m=s.match(/(?:BOXID|BOX|BOX_ID)[:=\\s-]*([A-Z0-9-]+).*?SKU[:=\\s-]*([A-Z0-9-]+).*?(?:QTY|QUANTITY)[:=\\s]*(\\d+)/i);return m?{boxId:m[1],sku:m[2],qty:+m[3],name:'Incoming item'}:null};
 const resolve=(id)=>setExceptions(exceptions.map(e=>e.id===id?{...e,status:'Resolved'}:e));
 const startCamera=()=>{if(!window.Html5Qrcode){setScan('BOX-1042');process('BOX-1042');return}setCamera(true);setTimeout(()=>{const qr=new Html5Qrcode('qr-reader');qr.start({facingMode:'environment'},{fps:10,qrbox:220},text=>{qr.stop().catch(()=>{});setCamera(false);process(text)},()=>{}).catch(()=>{setCamera(false);setNotice({red:true,text:'Camera unavailable · use BoxID entry instead'})})},50)};
 return <div className="shell"><aside className="side"><div className="brand">dock<span>flow</span></div><nav className="nav">{['Receiving','Locations','Search','Exceptions'].map((x,i)=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}><b>{['⌁','▦','⌕','!'][i]}</b><span>{x}</span></button>)}</nav><div className="user"><strong>Jordan Lee</strong>Receiving lead · Dock 4</div></aside><main className="main"><header className="top"><h1>{tab}</h1><span className="date">Sat, Sep 12, 2026 · <b>Demo mode</b></span></header><div className="content">{tab==='Receiving'?<><div className="cards"><Stat l="Received today" v={received} h="+12% vs yesterday"/><Stat l="Boxes processed" v="23" h="4 in progress"/><Stat l="Open exceptions" v={exceptions.filter(e=>e.status==='Open').length} h="Needs attention"/><Stat l="Dock utilization" v="72%" h="On track"/></div><div className="grid"><section className="panel"><div className="panel-head"><h2>Receive a box</h2><span className="pill green">● Scanner ready</span></div><div className="scanner"><span className="scan-icon">▣</span><strong>Scan QR label</strong><p>Use your camera or enter a BoxID below</p>{camera?<div id="qr-reader" style={{maxWidth:280,margin:'0 auto'}}/>:<><div className="input-row"><input placeholder="e.g. BOX-1042" value={scan} onChange={e=>setScan(e.target.value)} onKeyDown={e=>e.key==='Enter'&&process(scan)}/><button className="btn primary" onClick={()=>process(scan)}>Receive</button></div><button className="btn subtle" style={{marginTop:10}} onClick={startCamera}>▣ Use camera</button></>}</div>{last&&<div className="result"><strong>✓ {last.boxId} · {last.name}</strong><small>{last.sku} · {last.qty} units · destination advanced automatically</small></div>}<p className="small" style={{marginTop:18}}>Demo labels: BOX-1042, BOX-1043, BOX-1044, BOX-1045</p></section><section className="panel"><h2>Today's routing</h2><div className="bars">{items.map(x=><div className="barline" key={x.sku}><span>{x.loc}</span><div className="bar"><i style={{width:`${Math.round(x.done/x.cap*100)}%`}}/></div><b>{x.done}/{x.cap}</b></div>)}</div><hr style={{border:0,borderTop:'1px solid var(--line)',margin:'24px 0'}}/><div className="panel-head"><h2>Recent scans</h2><button className="ghost" onClick={()=>setTab('Search')}>View all</button></div><table className="table"><tbody><tr><td><b>BOX-1041</b><br/><span className="small">SKU-CED-03 · 10 units</span></td><td><span className="pill green">A-01-03</span></td><td className="small">2m ago</td></tr><tr><td><b>BOX-1040</b><br/><span className="small">SKU-ALP-01 · 24 units</span></td><td><span className="pill green">A-01-03</span></td><td className="small">8m ago</td></tr></tbody></table></section></div></>:tab==='Locations'?<Locations items={items}/>:tab==='Search'?<Search/>:<Exceptions exceptions={exceptions} resolve={resolve}/>}</div>{notice&&<div className={'toast '+(notice.red?'red':'')}>{notice.text}</div>}</main></div>}
function Stat(p){return <div className="card"><div className="label">{p.l}</div><div className="value">{p.v}</div><div className="hint">↗ {p.h}</div></div>}
function Locations({items}){return <section className="panel"><div className="panel-head"><h2>Location capacity</h2><span className="small">3 active zones</span></div><table className="table"><thead><tr><th>Location</th><th>SKU</th><th>Filled</th><th>Status</th></tr></thead><tbody>{items.map(x=><tr key={x.loc}><td><b>{x.loc}</b></td><td>{x.sku}<br/><span className="small">{x.name}</span></td><td>{x.done} / {x.cap}<div className="bar"><i style={{width:`${x.done/x.cap*100}%`}}/></div></td><td><span className={'pill '+(x.done/x.cap>.9?'amber':'green')}>{x.done/x.cap>.9?'Nearly full':'Receiving'}</span></td></tr>)}</tbody></table></section>}
function Search(){const [q,setQ]=useState('');let rows=['BOX-1042 · SKU-ALP-01 · 24 units · A-01-03','BOX-1041 · SKU-CED-03 · 10 units · C-01-02','BOX-1040 · SKU-ALP-01 · 24 units · A-01-03'];return <section className="panel"><h2>Search receiving history</h2><input className="search" placeholder="Search BoxID or SKU…" value={q} onChange={e=>setQ(e.target.value)}/><table className="table"><tbody>{rows.filter(r=>r.toLowerCase().includes(q.toLowerCase())).map(r=><tr key={r}><td>{r.split(' · ')[0]}</td><td>{r.split(' · ').slice(1).join(' · ')}</td><td><span className="pill green">Complete</span></td></tr>)}</tbody></table></section>}
function Exceptions({exceptions,resolve}){return <section className="panel"><div className="panel-head"><h2>Exceptions</h2><span className="pill red">{exceptions.filter(e=>e.status==='Open').length} open</span></div>{exceptions.map(e=><div className="exception" key={e.id}><div><strong>{e.box} <span className={'pill '+(e.status==='Resolved'?'green':'red')}>{e.status}</span></strong><small>{e.reason}</small></div>{e.status==='Open'&&<button className="btn subtle" onClick={()=>resolve(e.id)}>Resolve</button>}</div>)}</section>}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
