const {useEffect,useState}=React;
const api=async(path,opts)=>{const r=await fetch(path,opts);const data=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw Object.assign(new Error(data.error||'Request failed'),{status:r.status,data});return data};
const parseQR=s=>{const m=s.match(/(?:BOXID|BOX|BOX_ID)[:=\s-]*([A-Z0-9-]+).*?SKU[:=\s-]*([A-Z0-9-]+).*?(?:QTY|QUANTITY)[:=\s]*(\d+)/i);return m?{boxId:m[1],sku:m[2],qty:+m[3]}:null};
function App(){
 const [tab,setTab]=useState('Receiving'),[scan,setScan]=useState(''),[notice,setNotice]=useState(null),[success,setSuccess]=useState(null),[items,setItems]=useState([]),[assignments,setAssignments]=useState([]),[history,setHistory]=useState([]),[exceptions,setExceptions]=useState([]),[day,setDay]=useState(null),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [loc,as,hist,ex,d]=await Promise.all([api('/api/locations'),api('/api/assignments'),api('/api/history'),api('/api/exceptions'),api('/api/day')]);setItems(loc);setAssignments(as);setHistory(hist);setExceptions(ex);setDay(d)}catch(e){setNotice({red:true,text:e.message})}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(null),5000);return()=>clearTimeout(t)}},[notice]);
 const process=async raw=>{const key=raw.trim().toUpperCase();let info=parseQR(key);if(!info)try{info=await api(`/api/boxes/${encodeURIComponent(key)}`)}catch{setNotice({red:true,text:'Could not find that box. Scan a label or enter a BoxID.'});return}try{const event=await api('/api/scans',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...info,userId:'receiving-lead',deviceId:'dock-web'})});setSuccess({info,event});setScan('');await load();setTimeout(()=>setSuccess(null),3500)}catch(e){setNotice({red:true,text:e.message==='NO AVAILABLE SORTING LOCATION'?'NO AVAILABLE SORTING LOCATION':e.status===409?`Duplicate · ${info.boxId} was already received`:`Unable to receive: ${e.message}`})}};
 const reset=async()=>{try{await api('/api/day/reset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:'supervisor'})});setNotice({text:'Daily assignments reset. Historical scans remain searchable.'});await load()}catch(e){setNotice({red:true,text:e.message})}};
 const resolve=async id=>{try{await api(`/api/exceptions/${id}/resolve`,{method:'POST'});await load()}catch(e){setNotice({red:true,text:e.message})}};
 if(loading)return <div className="empty">Loading DockFlow…</div>;
 return <div className="shell"><aside className="side"><div className="brand">dock<span>flow</span></div><nav className="nav">{['Receiving','Locations','Search','Exceptions'].map((x,i)=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}><b>{['⌁','▦','⌕','!'][i]}</b><span>{x}</span></button>)}</nav><div className="user"><strong>Receiving lead</strong>Production workspace</div></aside><main className="main"><header className="top"><h1>{tab}</h1><span className="date">{day?.warehouseDate||'—'} · <b>PostgreSQL</b></span></header><div className="content">{tab==='Receiving'?<Receiving items={items} assignments={assignments} history={history} exceptions={exceptions} scan={scan} setScan={setScan} process={process} success={success} setTab={setTab}/>:tab==='Locations'?<Locations items={items} assignments={assignments} day={day} reset={reset}/>:tab==='Search'?<Search history={history}/>:<Exceptions exceptions={exceptions} resolve={resolve}/>}</div>{notice&&<div className={'toast '+(notice.red?'red':'')}>{notice.text}</div>}</main></div>
}
function Receiving({assignments,history,exceptions,scan,setScan,process,success,setTab}){const received=history.reduce((n,x)=>n+x.qty,0);return <><div className="cards"><Stat l="Received units today" v={received}/><Stat l="Boxes processed" v={history.filter(x=>x.warehouseDate===new Date().toISOString().slice(0,10)).length}/><Stat l="Open exceptions" v={exceptions.filter(e=>e.status==='open').length}/><Stat l="Assigned locations" v={assignments.length+' / 50'}/></div><div className="grid"><section className="panel"><div className="panel-head"><h2>Receive a box</h2><span className="pill green">● Scanner ready</span></div>{success?<div className="success-screen"><div className="success-check">✓</div><h2>Destination confirmed</h2><div className="location-destination">LOCATION {success.event.destination}</div><strong className="move-box">MOVE BOX TO {success.event.destination}</strong><p>{success.event.boxId} · {success.event.sku}</p><small>Ready for next scan</small></div>:<div className="scanner"><span className="scan-icon">▣</span><strong>Scan QR label</strong><p>Use a QR payload or enter a BoxID below</p><div className="input-row"><input placeholder="Enter BoxID or QR payload" value={scan} onChange={e=>setScan(e.target.value)} onKeyDown={e=>e.key==='Enter'&&process(scan)}/><button className="btn primary" onClick={()=>process(scan)}>Receive</button></div></div>}</section><section className="panel"><div className="panel-head"><h2>Today’s assignments</h2><button className="ghost" onClick={()=>setTab('Locations')}>View all</button></div><div className="bars">{assignments.slice(0,8).map(x=><div className="barline" key={x.location}><span>LOCATION {x.location}</span><div className="bar"><i style={{width:`${Math.min(100,x.filled/x.capacity*100)}%`}}/></div><b>{x.filled}/{x.capacity}</b></div>)}</div><hr style={{border:0,borderTop:'1px solid var(--line)',margin:'24px 0'}}/><div className="panel-head"><h2>Recent scans</h2><button className="ghost" onClick={()=>setTab('Search')}>View all</button></div><table className="table"><tbody>{history.slice(0,3).map(x=><tr key={x.boxId}><td><b>{x.boxId}</b><br/><span className="small">{x.sku} · {x.qty} units</span></td><td><span className="pill green">LOCATION {x.loc}</span></td><td className="small">{new Date(x.scannedAt).toLocaleTimeString()}</td></tr>)}</tbody></table></section></div></>}
function Stat({l,v}){return <div className="card"><div className="label">{l}</div><div className="value">{v}</div><div className="hint">Live from database</div></div>}
function Locations({items,assignments,day,reset}){return <section className="panel"><div className="panel-head"><div><h2>Numbered sorting locations</h2><p className="small">{day?.warehouseDate} · exactly 50 permanent physical locations</p></div><button className="btn primary" onClick={reset}>Start New Day / Reset</button></div><table className="table"><thead><tr><th>Location</th><th>Today's SKU</th><th>Filled</th><th>Status</th></tr></thead><tbody>{items.map(x=>{const a=assignments.find(y=>y.location===x.location);return <tr key={x.location}><td><b>LOCATION {x.location}</b></td><td>{a?.sku||'Available'}</td><td>{a?`${a.filled} / ${a.capacity}`:'—'}{a&&<div className="bar"><i style={{width:`${Math.min(100,a.filled/a.capacity*100)}%`}}/></div>}</td><td><span className={'pill '+(a?'green':'')}>{a?'Assigned':'Available'}</span></td></tr>})}</tbody></table></section>}
function Search({history}){const [q,setQ]=useState('');const rows=history.filter(r=>`${r.boxId} ${r.sku} ${r.loc}`.toLowerCase().includes(q.toLowerCase()));return <section className="panel"><h2>Search receiving history</h2><input className="search" placeholder="Search BoxID, SKU, or location…" value={q} onChange={e=>setQ(e.target.value)}/><table className="table"><tbody>{rows.map(r=><tr key={`${r.boxId}-${r.scannedAt}`}><td>{r.boxId}</td><td>{r.sku} · {r.qty} units · LOCATION {r.loc}</td><td>{new Date(r.scannedAt).toLocaleString()}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No scans found.</div>}</section>}
function Exceptions({exceptions,resolve}){return <section className="panel"><div className="panel-head"><h2>Exceptions</h2><span className="pill red">{exceptions.filter(e=>e.status==='open').length} open</span></div>{exceptions.map(e=><div className="exception" key={e.id}><div><strong>{e.box||'Unassigned'} <span className={'pill '+(e.status==='resolved'?'green':'red')}>{e.status}</span></strong><small>{e.reason}</small></div>{e.status==='open'&&<button className="btn subtle" onClick={()=>resolve(e.id)}>Resolve</button>}</div>)}{!exceptions.length&&<div className="empty">No exceptions.</div>}</section>}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
