CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS products (sku TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS locations (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), code TEXT UNIQUE NOT NULL, capacity INTEGER NOT NULL CHECK (capacity > 0), sku TEXT REFERENCES products(sku));
CREATE TABLE IF NOT EXISTS routing_rules (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), sku TEXT NOT NULL REFERENCES products(sku), priority INTEGER NOT NULL DEFAULT 1, location_code TEXT NOT NULL REFERENCES locations(code), capacity INTEGER NOT NULL CHECK (capacity > 0), active BOOLEAN NOT NULL DEFAULT true, UNIQUE (sku,priority), UNIQUE (location_code));
CREATE TABLE IF NOT EXISTS boxes (box_id TEXT PRIMARY KEY, sku TEXT NOT NULL REFERENCES products(sku), quantity INTEGER NOT NULL CHECK (quantity > 0), received_at TIMESTAMPTZ, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','received','cancelled')));
CREATE TABLE IF NOT EXISTS scan_events (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), box_id TEXT NOT NULL REFERENCES boxes(box_id), sku TEXT NOT NULL REFERENCES products(sku), qty INTEGER NOT NULL CHECK(qty > 0), destination TEXT NOT NULL, user_id TEXT NOT NULL, device_id TEXT NOT NULL, inbound_id TEXT, client_id TEXT, box_sequence INTEGER, scanned_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(box_id));
CREATE TABLE IF NOT EXISTS exceptions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), box_id TEXT REFERENCES boxes(box_id), reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','resolved')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), resolved_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS scan_events_time_idx ON scan_events(scanned_at DESC);
CREATE INDEX IF NOT EXISTS scan_events_search_idx ON scan_events(box_id,sku);
